name: "Release PyPI"
description: "Release PyPI"
runs:
  using: "composite"
  steps:
    - name: Release PyPI
      shell: bash
      run: |
        uv publish --publish-url https://upload.pypi.org/legacy/ --trusted-publishing always
