name: Tests

on:
  push:
    branches:
      - "develop"
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  linux-deployment-test:
    runs-on: ubuntu-latest
    name: "Linux Deployment Test"
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run essential tests
        timeout-minutes: 10
        run: |
          uv run pytest \
            -n auto \
            --cov src \
            --timeout 30 \
            -o junit_suite_name="linux-deployment" \
            tests/unit

      - uses: ./.github/actions/report
        with:
          flag: linux-deployment
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

